name: CI/CD Pipeline for Django with Github and EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment (optional, for testing locally)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Step 3: Deploy and Run Django Server on EC2
      - name: Deploy and Run Django Server on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          
          # Create a temporary SSH key file
          echo "${EC2_KEY}" > private_key.pem
          chmod 600 private_key.pem

          # Connect to EC2 and execute commands
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'

          
          # Navigate to the project directory
          cd ~/ec2-test
          source venv/bin/activate
          git remote -v
          git pull origin main --no-edit
          cd FlexonFolder/EC2_django_demo
          pip install -r requirements.txt
          pkill -f runserver
          nohup python manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &

          EOF

